version: '3'
services:
  flask:
    build: ./backend
    container_name: backend-flask
    environment:
      # proda olmayacaq
     # - FLASK_ENV=development
      - PYTHONUNBUFFERED=False                   


    restart: on-failure
    volumes:
      - ./backend:/backend
    ports:
    #xarici port: konteynerin oz portu
      - "5003:5000"
    command: python Main.py